const mongoose=require('mongoose')
const empSchema=mongoose.Schema({
    name:{
        type:String,
        required:true,
    },
    email:{
        type:String,
        required:true,
    },
    password:{
        type:String,
        required:true,
    },
    age:{
        type:String,
        required:true,
    },
    designation:{
        type:String,
        required:true,
    },
    role:{
        type:String,
        required:true,
    },
    phone:{
        type:String,
        required:true,
    },
    salary:{
        type:String,
        required:true,
    },
    created_date:{
        type:String,
        required:true,
    },
    updated_date:{
        type:String,
        required:true,
    },
    status:{
        type:Boolean,
        required:true,
    },
    managerId:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Manager',
        required:true,
    }
});
const Employee=mongoose.model('Employee',empSchema)
module.exports=Employee;